import { normalizeCoordinates } from './patterns.js';

const GLIDER = [
  [1, 0],
  [2, 1],
  [0, 2],
  [1, 2],
  [2, 2],
];

const LWSS = [
  [1, 0],
  [4, 0],
  [0, 1],
  [0, 2],
  [4, 2],
  [0, 3],
  [1, 3],
  [2, 3],
  [3, 3],
];

const PULSAR = [
  [2, 0],
  [3, 0],
  [4, 0],
  [8, 0],
  [9, 0],
  [10, 0],
  [0, 2],
  [5, 2],
  [7, 2],
  [12, 2],
  [0, 3],
  [5, 3],
  [7, 3],
  [12, 3],
  [0, 4],
  [5, 4],
  [7, 4],
  [12, 4],
  [2, 5],
  [3, 5],
  [4, 5],
  [8, 5],
  [9, 5],
  [10, 5],
  [2, 7],
  [3, 7],
  [4, 7],
  [8, 7],
  [9, 7],
  [10, 7],
  [0, 8],
  [5, 8],
  [7, 8],
  [12, 8],
  [0, 9],
  [5, 9],
  [7, 9],
  [12, 9],
  [0, 10],
  [5, 10],
  [7, 10],
  [12, 10],
  [2, 12],
  [3, 12],
  [4, 12],
  [8, 12],
  [9, 12],
  [10, 12],
];

const GOSPER_GUN = [
  [0, 4],
  [0, 5],
  [1, 4],
  [1, 5],
  [10, 4],
  [10, 5],
  [10, 6],
  [11, 3],
  [11, 7],
  [12, 2],
  [12, 8],
  [13, 2],
  [13, 8],
  [14, 5],
  [15, 3],
  [15, 7],
  [16, 4],
  [16, 5],
  [16, 6],
  [17, 5],
  [20, 2],
  [20, 3],
  [20, 4],
  [21, 2],
  [21, 3],
  [21, 4],
  [22, 1],
  [22, 5],
  [24, 0],
  [24, 1],
  [24, 5],
  [24, 6],
  [34, 2],
  [34, 3],
  [35, 2],
  [35, 3],
];

const R_PENTOMINO = [
  [1, 0],
  [2, 0],
  [0, 1],
  [1, 1],
  [1, 2],
];

const DIEHARD = [
  [6, 0],
  [0, 1],
  [1, 1],
  [1, 2],
  [5, 2],
  [6, 2],
  [7, 2],
];

const ACORN = [
  [1, 0],
  [3, 1],
  [0, 2],
  [1, 2],
  [4, 2],
  [5, 2],
  [6, 2],
];

function at(coordinates, offsetX, offsetY) {
  return coordinates.map(([x, y]) => [x + offsetX, y + offsetY]);
}

function combine(parts) {
  return normalizeCoordinates(parts.flat());
}

export const presets = [
  {
    id: 'block',
    name: 'Block',
    note: 'The simplest still life: four cells that remain unchanged forever.',
    coordinates: [
      [0, 0],
      [1, 0],
      [0, 1],
      [1, 1],
    ],
  },
  {
    id: 'beehive',
    name: 'Beehive',
    note: 'A six-cell still life that shows how local balance can create permanence.',
    coordinates: [
      [1, 0],
      [2, 0],
      [0, 1],
      [3, 1],
      [1, 2],
      [2, 2],
    ],
  },
  {
    id: 'loaf',
    name: 'Loaf',
    note: 'A slightly asymmetric still life: stable, compact, and surprisingly elegant.',
    coordinates: [
      [1, 0],
      [2, 0],
      [0, 1],
      [3, 1],
      [1, 2],
      [3, 2],
      [2, 3],
    ],
  },
  {
    id: 'boat',
    name: 'Boat',
    note: 'A five-cell still life that looks almost like a stopped glider.',
    coordinates: [
      [0, 0],
      [1, 0],
      [0, 1],
      [2, 1],
      [1, 2],
    ],
  },
  {
    id: 'tub',
    name: 'Tub',
    note: 'A tiny four-cell diamond that stays perfectly still.',
    coordinates: [
      [1, 0],
      [0, 1],
      [2, 1],
      [1, 2],
    ],
  },
  {
    id: 'blinker',
    name: 'Blinker',
    note: 'The smallest oscillator: a line flips orientation every generation.',
    coordinates: [
      [0, 1],
      [1, 1],
      [2, 1],
    ],
  },
  {
    id: 'toad',
    name: 'Toad',
    note: 'A period-2 oscillator where two offset rows trade shape back and forth.',
    coordinates: [
      [1, 0],
      [2, 0],
      [3, 0],
      [0, 1],
      [1, 1],
      [2, 1],
    ],
  },
  {
    id: 'beacon',
    name: 'Beacon',
    note: 'Two blocks blink at their touching corners, creating a clean period-2 pulse.',
    coordinates: [
      [0, 0],
      [1, 0],
      [0, 1],
      [1, 1],
      [2, 2],
      [3, 2],
      [2, 3],
      [3, 3],
    ],
  },
  {
    id: 'glider',
    name: 'Glider',
    note: 'The smallest spaceship: it translates diagonally forever on a wrapped world.',
    coordinates: [
      [1, 0],
      [2, 1],
      [0, 2],
      [1, 2],
      [2, 2],
    ],
  },
  {
    id: 'lwss',
    name: 'Lightweight spaceship',
    note: 'A compact moving pattern that travels horizontally through empty space.',
    coordinates: [
      [1, 0],
      [4, 0],
      [0, 1],
      [0, 2],
      [4, 2],
      [0, 3],
      [1, 3],
      [2, 3],
      [3, 3],
    ],
  },
  {
    id: 'pulsar',
    name: 'Pulsar',
    note: 'A period-3 oscillator with a beautifully symmetric breathing rhythm.',
    coordinates: [
      [2, 0],
      [3, 0],
      [4, 0],
      [8, 0],
      [9, 0],
      [10, 0],
      [0, 2],
      [5, 2],
      [7, 2],
      [12, 2],
      [0, 3],
      [5, 3],
      [7, 3],
      [12, 3],
      [0, 4],
      [5, 4],
      [7, 4],
      [12, 4],
      [2, 5],
      [3, 5],
      [4, 5],
      [8, 5],
      [9, 5],
      [10, 5],
      [2, 7],
      [3, 7],
      [4, 7],
      [8, 7],
      [9, 7],
      [10, 7],
      [0, 8],
      [5, 8],
      [7, 8],
      [12, 8],
      [0, 9],
      [5, 9],
      [7, 9],
      [12, 9],
      [0, 10],
      [5, 10],
      [7, 10],
      [12, 10],
      [2, 12],
      [3, 12],
      [4, 12],
      [8, 12],
      [9, 12],
      [10, 12],
    ],
  },
  {
    id: 'pentadecathlon',
    name: 'Pentadecathlon',
    note: 'A stable-looking period-15 oscillator that takes its time returning home.',
    coordinates: [
      [1, 0],
      [2, 0],
      [0, 1],
      [3, 1],
      [1, 2],
      [2, 2],
      [1, 3],
      [2, 3],
      [1, 4],
      [2, 4],
      [1, 5],
      [2, 5],
      [0, 6],
      [3, 6],
      [1, 7],
      [2, 7],
    ],
  },
  {
    id: 'traffic-light',
    name: 'Traffic light',
    note: 'A symmetric burst that quickly becomes four blinkers around a center.',
    coordinates: [
      [4, 0],
      [4, 1],
      [4, 2],
      [0, 4],
      [1, 4],
      [2, 4],
      [6, 4],
      [7, 4],
      [8, 4],
      [4, 6],
      [4, 7],
      [4, 8],
    ],
  },
  {
    id: 'small-exploder',
    name: 'Small exploder',
    note: 'A compact seed that blooms outward, then leaves small debris behind.',
    coordinates: [
      [1, 0],
      [0, 1],
      [1, 1],
      [2, 1],
      [0, 2],
      [2, 2],
      [1, 3],
    ],
  },
  {
    id: 'ten-cell-row',
    name: 'Ten-cell row',
    note: 'A simple row that throws off sparks before breaking into smaller objects.',
    coordinates: [
      [0, 0],
      [1, 0],
      [2, 0],
      [3, 0],
      [4, 0],
      [5, 0],
      [6, 0],
      [7, 0],
      [8, 0],
      [9, 0],
    ],
  },
  {
    id: 'glider-pair',
    name: 'Glider pair',
    note: 'Two gliders launched apart: useful for watching motion across the wrapped world.',
    coordinates: [
      [1, 0],
      [2, 1],
      [0, 2],
      [1, 2],
      [2, 2],
      [13, 10],
      [11, 11],
      [13, 11],
      [12, 12],
      [13, 12],
    ],
  },
  {
    id: 'gosper-gun',
    name: 'Gosper glider gun',
    note: 'The classic generator: a stable machine that emits gliders again and again.',
    coordinates: [
      [0, 4],
      [0, 5],
      [1, 4],
      [1, 5],
      [10, 4],
      [10, 5],
      [10, 6],
      [11, 3],
      [11, 7],
      [12, 2],
      [12, 8],
      [13, 2],
      [13, 8],
      [14, 5],
      [15, 3],
      [15, 7],
      [16, 4],
      [16, 5],
      [16, 6],
      [17, 5],
      [20, 2],
      [20, 3],
      [20, 4],
      [21, 2],
      [21, 3],
      [21, 4],
      [22, 1],
      [22, 5],
      [24, 0],
      [24, 1],
      [24, 5],
      [24, 6],
      [34, 2],
      [34, 3],
      [35, 2],
      [35, 3],
    ],
  },
  {
    id: 'r-pentomino',
    name: 'R-pentomino',
    note: 'Only five cells, but it takes a surprisingly long time to settle.',
    coordinates: [
      [1, 0],
      [2, 0],
      [0, 1],
      [1, 1],
      [1, 2],
    ],
  },
  {
    id: 'diehard',
    name: 'Diehard',
    note: 'A small pattern famous for lasting many generations before disappearing.',
    coordinates: [
      [6, 0],
      [0, 1],
      [1, 1],
      [1, 2],
      [5, 2],
      [6, 2],
      [7, 2],
    ],
  },
  {
    id: 'acorn',
    name: 'Acorn',
    note: 'A tiny seed that grows into a long, complex transient before calming down.',
    coordinates: [
      [1, 0],
      [3, 1],
      [0, 2],
      [1, 2],
      [4, 2],
      [5, 2],
      [6, 2],
    ],
  },
  {
    id: 'gun-battery',
    name: 'Glider gun battery',
    note: 'Three Gosper guns staggered into a machine wall that throws streams across the board.',
    coordinates: combine([
      at(GOSPER_GUN, 0, 0),
      at(GOSPER_GUN, 0, 24),
      at(GOSPER_GUN, 0, 48),
    ]),
  },
  {
    id: 'spaceship-squadron',
    name: 'Spaceship squadron',
    note: 'A fleet of lightweight spaceships that makes motion obvious in the first few seconds.',
    coordinates: combine([
      at(LWSS, 0, 0),
      at(LWSS, 0, 10),
      at(LWSS, 0, 20),
      at(LWSS, 18, 4),
      at(LWSS, 18, 14),
      at(LWSS, 18, 24),
      at(LWSS, 36, 8),
      at(LWSS, 36, 18),
    ]),
  },
  {
    id: 'pulsar-constellation',
    name: 'Pulsar constellation',
    note: 'A field of period-3 oscillators: symmetrical, readable, and instantly alive.',
    coordinates: combine([
      at(PULSAR, 0, 0),
      at(PULSAR, 22, 0),
      at(PULSAR, 44, 0),
      at(PULSAR, 11, 20),
      at(PULSAR, 33, 20),
      at(PULSAR, 0, 40),
      at(PULSAR, 22, 40),
      at(PULSAR, 44, 40),
    ]),
  },
  {
    id: 'methuselah-garden',
    name: 'Methuselah garden',
    note: 'A spaced-out mix of famous long-lived seeds that keeps throwing off surprises.',
    coordinates: combine([
      at(R_PENTOMINO, 0, 0),
      at(ACORN, 18, 8),
      at(DIEHARD, 44, 2),
      at(R_PENTOMINO, 68, 18),
      at(ACORN, 84, 30),
      at(DIEHARD, 118, 16),
    ]),
  },
  {
    id: 'glider-fleet',
    name: 'Glider fleet',
    note: 'Many small spaceships launched in formation so the wrapped world feels alive.',
    coordinates: combine([
      at(GLIDER, 0, 0),
      at(GLIDER, 10, 7),
      at(GLIDER, 20, 14),
      at(GLIDER, 30, 21),
      at(GLIDER, 40, 28),
      at(GLIDER, 50, 35),
      at(GLIDER, 60, 42),
      at(GLIDER, 70, 49),
      at(GLIDER, 80, 56),
    ]),
  },
  {
    id: 'blinker-wave',
    name: 'Blinker wave',
    note: 'Rows of phase-shifted blinkers that turn a tiny oscillator into a visible rhythm wall.',
    coordinates: combine([
      ...Array.from({ length: 12 }, (_, row) => (
        Array.from({ length: 12 }, (_, column) => at([[0, 0], [1, 0], [2, 0]], column * 6 + (row % 2) * 3, row * 5))
      )).flat(),
    ]),
  },
];

export const presetGroups = [
  {
    id: 'showcase',
    title: 'Showcase',
    note: 'Bigger starts that immediately show motion, growth, and machines.',
    ids: ['gun-battery', 'spaceship-squadron', 'pulsar-constellation', 'methuselah-garden', 'glider-fleet', 'blinker-wave'],
  },
  {
    id: 'motion',
    title: 'Motion',
    note: 'Patterns that pulse, move, fire, or unfold.',
    ids: ['blinker', 'toad', 'beacon', 'pulsar', 'pentadecathlon', 'glider', 'lwss', 'gosper-gun', 'traffic-light', 'small-exploder', 'ten-cell-row', 'glider-pair', 'r-pentomino', 'diehard', 'acorn'],
  },
  {
    id: 'basics',
    title: 'Basics',
    note: 'Small reference shapes for learning why some cells survive.',
    ids: ['block', 'beehive', 'loaf', 'boat', 'tub'],
  },
];
